### ISSUE TITLE
Update for version 2.3.0?

### ISSUE THREAD

**Issue by gapplef** [soumyaDghosh/kooha-snap#1]

**Comment by soumyaDghosh** [comment]
Until `snapcraft` version `8.3.0` becomes stable, which brings out gnome extension for core24 under stable usage, I can't update this

**Comment by gapplef** [comment]
:ok_hand: Got it! Thanks a lot!

**Comment by soumyaDghosh** [comment]
Hi @gapplef I have updated it to stable. Thanks a lot for understanding. On a side if you do love my work, please do consider supporting me. Thanks again! Have a great day. <3
